/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface AppSpinner {
    }
    interface AppStockFinder {
    }
    interface AppStockPrice {
        "stockSymbol": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppSpinnerElement extends Components.AppSpinner, HTMLStencilElement {
    }
    var HTMLAppSpinnerElement: {
        prototype: HTMLAppSpinnerElement;
        new (): HTMLAppSpinnerElement;
    };
    interface HTMLAppStockFinderElement extends Components.AppStockFinder, HTMLStencilElement {
    }
    var HTMLAppStockFinderElement: {
        prototype: HTMLAppStockFinderElement;
        new (): HTMLAppStockFinderElement;
    };
    interface HTMLAppStockPriceElement extends Components.AppStockPrice, HTMLStencilElement {
    }
    var HTMLAppStockPriceElement: {
        prototype: HTMLAppStockPriceElement;
        new (): HTMLAppStockPriceElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-spinner": HTMLAppSpinnerElement;
        "app-stock-finder": HTMLAppStockFinderElement;
        "app-stock-price": HTMLAppStockPriceElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppSpinner {
    }
    interface AppStockFinder {
        "onUcSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface AppStockPrice {
        "stockSymbol"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-spinner": AppSpinner;
        "app-stock-finder": AppStockFinder;
        "app-stock-price": AppStockPrice;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-spinner": LocalJSX.AppSpinner & JSXBase.HTMLAttributes<HTMLAppSpinnerElement>;
            "app-stock-finder": LocalJSX.AppStockFinder & JSXBase.HTMLAttributes<HTMLAppStockFinderElement>;
            "app-stock-price": LocalJSX.AppStockPrice & JSXBase.HTMLAttributes<HTMLAppStockPriceElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
